import { Inter } from "next/font/google";
import "./globals.css";
// import Navbar from "../components/navbar";
import CategoryDisplaySection from "@/components/CategoryDisplaySection";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CategoryDisplaySection />
      <CategoryDisplaySection />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
